# Generated by Django 5.0 on 2023-12-19 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0002_caste_fatherprofile_hobbies_religion_profile_caste_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Sect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to='matrimony.sect'),
        ),
    ]
