# Generated by Django 5.0 on 2023-12-19 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0003_profile_sect'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hobbies',
            options={'verbose_name_plural': 'Hobbies'},
        ),
    ]
