# Generated by Django 5.0 on 2023-12-26 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0004_alter_hobbies_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='father',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependent', to='matrimony.fatherprofile'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='hobbies',
            field=models.ManyToManyField(related_name='profiles', to='matrimony.hobbies'),
        ),
    ]
